"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](fg:blue)\
$os\
[](fg:blue bg:green)\
$directory\
[](fg:green bg:yellow)\
$git_branch\
$git_status\
[](fg:yellow)\
$fill\
[](fg:magenta)\
$cmd_duration\
$time\
[ ](fg:magenta)\
$line_break$character"""

palette = 'kanagawa_dragon'

[palettes.kanagawa_dragon]
black = "#0d0c0c" 
red = "#c4746e" 
green = "#8a9a7b" 
yellow = "#c4b28a" 
blue = "#8ba4b0" 
magenta = "#a292a3" 
cyan = "#8ea4a2" 
white = "#C8C093" 
bright-black = "#a6a69c" 
bright-red = "#E46876" 
bright-green = "#87a987" 
bright-yellow = "#E6C384" 
bright-blue = "#7FB4CA" 
bright-magenta = "#938AA9" 
bright-cyan = "#7AA89F" 
bright-white = "#c5c9c5" 

[fill]
symbol=' '

[os]
disabled = false
style = "bg:blue fg:black"

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[directory]
style = "fg:black bg:green"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
read_only = " 󰌾"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[time]
disabled = false
time_format = "%R"
style = "fg:black bg:magenta"
format = '[  $time ]($style)'

[cmd_duration]
format = '[ $duration ]($style)'
style = 'fg:black bg:magenta'
min_time = 500
disabled = false

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[󱞩](bold fg:bright-green)'
error_symbol = '[󱞩](bold fg:bright-red)'
vimcmd_symbol = '[󱞥](bold fg:bright-green)'
vimcmd_replace_one_symbol = '[󱞥](bold fg:red)'
vimcmd_replace_symbol = '[󱞥](bold fg:red)'
vimcmd_visual_symbol = '[󱞥](bold fg:yellow)'

[git_branch]
symbol = ""
style = "bg:yellow"
format = '[[ $symbol $branch ](fg:black bg:yellow)]($style)'

[git_status]
style = "bg:yellow"
format = '[[($all_status$ahead_behind )](fg:black bg:yellow)]($style)'
